default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: ty56vy
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: tutorial_dev

test:
  <<: *default
  database: tutorial_test

production:
  <<: *default
  database: tutorial_prod
  username: root
  password: ty56vy
